//! WebAssembly bindings for MTG Forge
//!
//! This module provides WASM-compatible APIs for the MTG game engine,
//! enabling browser-based gameplay.
//!
//! ## Architecture
//!
//! The WASM build exposes a JavaScript-friendly API through `wasm-bindgen`:
//! - Game state is managed in Rust and serialized to JSON for JS consumption
//! - Player controllers receive choices via callbacks from JavaScript
//! - Card and deck data is loaded from pre-serialized bincode files
//!
//! ## Usage Example (JavaScript)
//!
//! ```javascript
//! import init, { WasmCardDatabase, WasmGame, version } from './mtg_forge_rs.js';
//!
//! async function main() {
//!     await init();
//!     console.log("MTG Forge version:", version());
//!
//!     // Load card and deck data (fetch from server)
//!     const cardsData = await fetch('/data/cards.bin').then(r => r.arrayBuffer());
//!     const decksData = await fetch('/data/decks.bin').then(r => r.arrayBuffer());
//!
//!     const cardDb = new WasmCardDatabase();
//!     cardDb.load_cards(new Uint8Array(cardsData));
//!     cardDb.load_decks(new Uint8Array(decksData));
//!
//!     // Create a game with loaded decks
//!     const game = WasmGame.from_database(cardDb, "white_weenie_classic", "mono_black_control");
//!     game.run_ai_game(100);
//! }
//! ```
//!
//! ## Limitations (compared to native)
//!
//! - No file system access (card/deck data must be provided from JS)
//! - No threading (single-threaded game loop)
//! - Token creation requires pre-loaded token definitions

#[cfg(all(feature = "wasm-tui", target_arch = "wasm32"))]
pub mod fancy_tui;

pub mod human_controller;
pub mod rich_input_controller;

#[cfg(target_arch = "wasm32")]
pub mod image_overlay;

pub use human_controller::{PendingChoice, WasmHumanController};
pub use rich_input_controller::WasmRichInputController;

use std::collections::HashMap;
use std::sync::Arc;
use wasm_bindgen::prelude::*;

use crate::core::PlayerId;
use crate::game::logger::OutputMode;
use crate::game::{
    GameLoop, GameState, HeuristicController, PlayerController, RandomController, VerbosityLevel, ZeroController,
};
use crate::loader::{CardDefinition, DeckEntry, DeckList};

/// Initialize the WASM module (called automatically)
#[wasm_bindgen(start)]
pub fn wasm_init() {
    // Set up panic hook for better error messages in browser console
    console_error_panic_hook_setup();
}

/// Set up console_error_panic_hook for better WASM error messages
fn console_error_panic_hook_setup() {
    // This provides better error messages in the browser console
    // when a panic occurs in Rust code
    std::panic::set_hook(Box::new(|panic_info| {
        let message = if let Some(s) = panic_info.payload().downcast_ref::<&str>() {
            s.to_string()
        } else if let Some(s) = panic_info.payload().downcast_ref::<String>() {
            s.clone()
        } else {
            "Unknown panic".to_string()
        };

        let location = panic_info
            .location()
            .map(|l| format!(" at {}:{}:{}", l.file(), l.line(), l.column()))
            .unwrap_or_default();

        web_sys::console::error_1(&format!("MTG Forge panic: {}{}", message, location).into());
    }));
}

/// Version information
#[wasm_bindgen]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// Check if WASM module is properly initialized
#[wasm_bindgen]
pub fn is_ready() -> bool {
    true
}

/// WASM-compatible card and deck database
///
/// Loads card definitions and deck lists from pre-serialized bincode data.
/// Use the `mtg export-wasm` command to generate the data files.
#[wasm_bindgen]
pub struct WasmCardDatabase {
    pub(crate) cards: HashMap<String, Arc<CardDefinition>>,
    pub(crate) decks: HashMap<String, DeckList>,
}

#[wasm_bindgen]
impl WasmCardDatabase {
    /// Create an empty card database
    #[wasm_bindgen(constructor)]
    pub fn new() -> WasmCardDatabase {
        WasmCardDatabase {
            cards: HashMap::new(),
            decks: HashMap::new(),
        }
    }

    /// Load cards from bincode data
    ///
    /// The data should be the contents of `cards.bin` generated by `mtg export-wasm`.
    /// Returns the number of cards loaded, or an error message.
    pub fn load_cards(&mut self, data: &[u8]) -> Result<u32, JsValue> {
        let cards: HashMap<String, CardDefinition> = bincode::deserialize(data)
            .map_err(|e| JsValue::from_str(&format!("Failed to deserialize cards: {}", e)))?;

        let count = cards.len() as u32;
        self.cards = cards.into_iter().map(|(k, v)| (k, Arc::new(v))).collect();

        web_sys::console::log_1(&format!("Loaded {} cards", count).into());
        Ok(count)
    }

    /// Load decks from bincode data
    ///
    /// The data should be the contents of `decks.bin` generated by `mtg export-wasm`.
    /// Returns the number of decks loaded, or an error message.
    pub fn load_decks(&mut self, data: &[u8]) -> Result<u32, JsValue> {
        let decks: HashMap<String, DeckList> = bincode::deserialize(data)
            .map_err(|e| JsValue::from_str(&format!("Failed to deserialize decks: {}", e)))?;

        let count = decks.len() as u32;
        self.decks = decks;

        web_sys::console::log_1(&format!("Loaded {} decks", count).into());
        Ok(count)
    }

    /// Get the number of loaded cards
    pub fn card_count(&self) -> u32 {
        self.cards.len() as u32
    }

    /// Get the number of loaded decks
    pub fn deck_count(&self) -> u32 {
        self.decks.len() as u32
    }

    /// Get a list of available deck names as JSON array
    pub fn get_deck_names_json(&self) -> String {
        let names: Vec<&String> = self.decks.keys().collect();
        serde_json::to_string(&names).unwrap_or_else(|_| "[]".to_string())
    }

    /// Get deck info as JSON (name, card count)
    pub fn get_deck_info_json(&self, deck_name: &str) -> String {
        if let Some(deck) = self.decks.get(deck_name) {
            let info = serde_json::json!({
                "name": deck_name,
                "main_deck_count": deck.total_cards(),
                "sideboard_count": deck.sideboard_size(),
                "unique_cards": deck.unique_card_names().len()
            });
            serde_json::to_string(&info).unwrap_or_else(|_| "{}".to_string())
        } else {
            format!("{{\"error\": \"Deck '{}' not found\"}}", deck_name)
        }
    }

    /// Check if a card is available in the database
    pub fn has_card(&self, card_name: &str) -> bool {
        self.cards.contains_key(card_name)
    }

    /// Check if a deck is available in the database
    pub fn has_deck(&self, deck_name: &str) -> bool {
        self.decks.contains_key(deck_name)
    }
}

impl Default for WasmCardDatabase {
    fn default() -> Self {
        Self::new()
    }
}

/// Controller type for WASM games
#[wasm_bindgen]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WasmControllerType {
    /// Always passes priority (does nothing)
    Zero,
    /// Makes random legal choices
    Random,
    /// Uses heuristic AI evaluation
    Heuristic,
    /// Human player (interactive input via UI)
    Human,
}

/// WASM-compatible game wrapper
///
/// This struct wraps the Rust GameState and provides a JavaScript-friendly API.
#[wasm_bindgen]
pub struct WasmGame {
    game: GameState,
    p1_controller_type: WasmControllerType,
    p2_controller_type: WasmControllerType,
    game_seed: u64,
}

#[wasm_bindgen]
impl WasmGame {
    /// Create a new game with two players (no decks)
    ///
    /// # Arguments
    /// * `p1_name` - Player 1's name
    /// * `p2_name` - Player 2's name
    /// * `starting_life` - Starting life total for both players
    #[wasm_bindgen(constructor)]
    pub fn new(p1_name: &str, p2_name: &str, starting_life: i32) -> WasmGame {
        let mut game = GameState::new_two_player(p1_name.to_string(), p2_name.to_string(), starting_life);

        // Configure logger for WASM: capture to memory, enable normal verbosity
        game.logger.set_output_mode(OutputMode::Memory);
        game.logger.set_verbosity(VerbosityLevel::Normal);

        WasmGame {
            game,
            p1_controller_type: WasmControllerType::Heuristic,
            p2_controller_type: WasmControllerType::Heuristic,
            game_seed: 0,
        }
    }

    /// Create a new game with decks from the card database
    ///
    /// # Arguments
    /// * `card_db` - The loaded card database
    /// * `p1_deck_name` - Name of player 1's deck
    /// * `p2_deck_name` - Name of player 2's deck
    /// * `starting_life` - Starting life total for both players
    /// * `seed` - Random seed for shuffling and game RNG
    pub fn from_database(
        card_db: &WasmCardDatabase,
        p1_deck_name: &str,
        p2_deck_name: &str,
        starting_life: i32,
        seed: u64,
    ) -> Result<WasmGame, JsValue> {
        // Look up decks
        let p1_deck = card_db
            .decks
            .get(p1_deck_name)
            .ok_or_else(|| JsValue::from_str(&format!("Deck '{}' not found", p1_deck_name)))?;
        let p2_deck = card_db
            .decks
            .get(p2_deck_name)
            .ok_or_else(|| JsValue::from_str(&format!("Deck '{}' not found", p2_deck_name)))?;

        // Create game state
        let mut game = GameState::new_two_player("P1".to_string(), "P2".to_string(), starting_life);
        game.seed_rng(seed);

        // Configure logger for WASM: capture to memory, enable normal verbosity
        game.logger.set_output_mode(OutputMode::Memory);
        game.logger.set_verbosity(VerbosityLevel::Normal);

        let p1_id = game.players[0].id;
        let p2_id = game.players[1].id;

        // Helper to add cards from a deck entry
        let add_deck_cards = |game: &mut GameState,
                              owner: PlayerId,
                              entry: &DeckEntry,
                              cards: &HashMap<String, Arc<CardDefinition>>|
         -> Result<(), String> {
            let card_def = cards
                .get(&entry.card_name)
                .ok_or_else(|| format!("Card '{}' not found in database", entry.card_name))?;

            for _ in 0..entry.count {
                let card_id = game.next_entity_id();
                let card = card_def.instantiate(card_id, owner);
                // Insert card into game's card registry
                game.cards.insert(card_id, card);
                // Add to player's library zone
                if let Some(zones) = game.get_player_zones_mut(owner) {
                    zones.library.add(card_id);
                }
            }
            Ok(())
        };

        // Add player 1's deck
        for entry in &p1_deck.main_deck {
            add_deck_cards(&mut game, p1_id, entry, &card_db.cards).map_err(|e| JsValue::from_str(&e))?;
        }

        // Add player 2's deck
        for entry in &p2_deck.main_deck {
            add_deck_cards(&mut game, p2_id, entry, &card_db.cards).map_err(|e| JsValue::from_str(&e))?;
        }

        // Shuffle libraries
        game.shuffle_library(p1_id);
        game.shuffle_library(p2_id);

        // Draw opening hands (7 cards each)
        for _ in 0..7 {
            let _ = game.draw_card(p1_id);
            let _ = game.draw_card(p2_id);
        }

        web_sys::console::log_1(
            &format!(
                "Created game: {} ({} cards) vs {} ({} cards)",
                p1_deck_name,
                p1_deck.total_cards(),
                p2_deck_name,
                p2_deck.total_cards()
            )
            .into(),
        );

        Ok(WasmGame {
            game,
            p1_controller_type: WasmControllerType::Heuristic,
            p2_controller_type: WasmControllerType::Heuristic,
            game_seed: seed,
        })
    }

    /// Set the controller type for player 1
    pub fn set_p1_controller(&mut self, controller_type: WasmControllerType) {
        self.p1_controller_type = controller_type;
    }

    /// Set the controller type for player 2
    pub fn set_p2_controller(&mut self, controller_type: WasmControllerType) {
        self.p2_controller_type = controller_type;
    }

    /// Set the game seed for reproducible games
    pub fn set_seed(&mut self, seed: u64) {
        self.game_seed = seed;
        self.game.seed_rng(seed);
    }

    /// Get the current game state as JSON
    ///
    /// Returns a JSON string containing:
    /// - Turn number
    /// - Current phase/step
    /// - Active player
    /// - Player life totals
    /// - Battlefield state (simplified)
    pub fn get_state_json(&self) -> String {
        // Create a simplified view of the game state for JS
        let state = WasmGameStateView {
            turn_number: self.game.turn.turn_number,
            current_step: format!("{:?}", self.game.turn.current_step),
            active_player_idx: self.game.turn.active_player_idx,
            players: self
                .game
                .players
                .iter()
                .map(|p| WasmPlayerView {
                    name: p.name.to_string(),
                    life: p.life,
                    lands_played: p.lands_played_this_turn,
                })
                .collect(),
            battlefield_count: self.game.battlefield.cards.len(),
            stack_count: self.game.stack.cards.len(),
        };

        serde_json::to_string(&state).unwrap_or_else(|e| format!("{{\"error\": \"{}\"}}", e))
    }

    /// Get the current turn number
    pub fn get_turn_number(&self) -> u32 {
        self.game.turn.turn_number
    }

    /// Get a player's life total
    pub fn get_player_life(&self, player_idx: usize) -> i32 {
        self.game.players.get(player_idx).map(|p| p.life).unwrap_or(0)
    }

    /// Check if the game is over
    pub fn is_game_over(&self) -> bool {
        // Check if any player has 0 or less life
        self.game.players.iter().any(|p| p.life <= 0)
    }

    /// Run the game with AI controllers until completion
    ///
    /// Returns a JSON string with the game result:
    /// - winner: player index or null for draw
    /// - turns_played: number of turns
    /// - end_reason: why the game ended
    pub fn run_ai_game(&mut self, max_turns: u32) -> String {
        let p1_id = self.game.players[0].id;
        let p2_id = self.game.players[1].id;

        let mut controller1: Box<dyn PlayerController> = match self.p1_controller_type {
            WasmControllerType::Zero => Box::new(ZeroController::new(p1_id)),
            WasmControllerType::Random => Box::new(RandomController::with_seed(p1_id, self.game_seed)),
            WasmControllerType::Heuristic => Box::new(HeuristicController::new(p1_id)),
            WasmControllerType::Human => todo!("Human controller not yet implemented for run_ai_game"),
        };

        let mut controller2: Box<dyn PlayerController> = match self.p2_controller_type {
            WasmControllerType::Zero => Box::new(ZeroController::new(p2_id)),
            WasmControllerType::Random => Box::new(RandomController::with_seed(p2_id, self.game_seed.wrapping_add(1))),
            WasmControllerType::Heuristic => Box::new(HeuristicController::new(p2_id)),
            WasmControllerType::Human => todo!("Human controller not yet implemented for run_ai_game"),
        };

        let mut game_loop = GameLoop::new(&mut self.game)
            .with_verbosity(VerbosityLevel::Normal)
            .with_max_turns(max_turns);

        let result = game_loop.run_game(controller1.as_mut(), controller2.as_mut());

        match result {
            Ok(game_result) => {
                let result_view = WasmGameResult {
                    winner: game_result
                        .winner
                        .map(|p| self.game.players.iter().position(|player| player.id == p).unwrap_or(0)),
                    turns_played: game_result.turns_played,
                    end_reason: format!("{:?}", game_result.end_reason),
                };
                serde_json::to_string(&result_view).unwrap_or_else(|e| format!("{{\"error\": \"{}\"}}", e))
            }
            Err(e) => format!("{{\"error\": \"{}\"}}", e),
        }
    }

    /// Run a single turn with AI controllers
    ///
    /// Returns true if game is still ongoing, false if game ended
    pub fn run_one_turn(&mut self) -> bool {
        let p1_id = self.game.players[0].id;
        let p2_id = self.game.players[1].id;

        let mut controller1: Box<dyn PlayerController> = match self.p1_controller_type {
            WasmControllerType::Zero => Box::new(ZeroController::new(p1_id)),
            WasmControllerType::Random => Box::new(RandomController::with_seed(p1_id, self.game_seed)),
            WasmControllerType::Heuristic => Box::new(HeuristicController::new(p1_id)),
            WasmControllerType::Human => todo!("Human controller not yet implemented for run_one_turn"),
        };

        let mut controller2: Box<dyn PlayerController> = match self.p2_controller_type {
            WasmControllerType::Zero => Box::new(ZeroController::new(p2_id)),
            WasmControllerType::Random => Box::new(RandomController::with_seed(p2_id, self.game_seed.wrapping_add(1))),
            WasmControllerType::Heuristic => Box::new(HeuristicController::new(p2_id)),
            WasmControllerType::Human => todo!("Human controller not yet implemented for run_one_turn"),
        };

        let mut game_loop = GameLoop::new(&mut self.game).with_verbosity(VerbosityLevel::Normal);

        match game_loop.run_turns(controller1.as_mut(), controller2.as_mut(), 1) {
            Ok(result) => result.winner.is_none(),
            Err(_) => false,
        }
    }

    /// Get the game logs as a JSON array of strings
    pub fn get_logs_json(&self) -> String {
        let logs: Vec<String> = self.game.logger.logs().iter().map(|l| l.message.clone()).collect();
        serde_json::to_string(&logs).unwrap_or_else(|_| "[]".to_string())
    }

    /// Clear the game logs
    pub fn clear_logs(&mut self) {
        self.game.logger.clear_logs();
    }
}

/// Simplified game state view for JSON serialization
#[derive(serde::Serialize)]
struct WasmGameStateView {
    turn_number: u32,
    current_step: String,
    active_player_idx: usize,
    players: Vec<WasmPlayerView>,
    battlefield_count: usize,
    stack_count: usize,
}

/// Simplified player view for JSON serialization
#[derive(serde::Serialize)]
struct WasmPlayerView {
    name: String,
    life: i32,
    lands_played: u8,
}

/// Game result for JSON serialization
#[derive(serde::Serialize)]
struct WasmGameResult {
    winner: Option<usize>,
    turns_played: u32,
    end_reason: String,
}
